//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Animal
    {
        public int ID { get; set; }
        public Nullable<int> ID_Animal { get; set; }
        public Nullable<int> ID_Application { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Applictioon Applictioon { get; set; }
    }
}
